### ISSUE TITLE
关于如何使用该语音包

### ISSUE THREAD

**Issue by zhl154381001** [Ran-ying/Klee-rainbow-fart#3]
关于如何使用该语音包麻烦出个教程啦，在webstorm上使用

**Comment by BlueStragglers** [comment]
作者发布的压缩包不能直接导入，因为压缩包下面还是文件夹，不是图片和语音文件。先解压，然后重新压缩，让压缩文件下面直接是图片和语音就可以了

**Comment by Ran-ying** [comment]
您好，该语音包基于 VSCode 的 [vscode-rainbow-fart](https://github.com/SaekiRaku/vscode-rainbow-fart) 拓展（[文档](https://github.com/SaekiRaku/vscode-rainbow-fart/blob/master/README.zh.md)），暂时无法在 WebStorm 上使用。
