### ISSUE TITLE
播放不了

### ISSUE THREAD

**Issue by hansjohn** [Ran-ying/Klee-rainbow-fart#4]
导入语音包后播放不了，用文件浏览器打开是可以播放的

**Comment by Ran-ying** [comment]
通常在 Vscode 开启后右下角会显示提示
![image](https://user-images.githubusercontent.com/62641267/187278896-4ed9c50a-57f6-46b5-86c0-8d4610a070de.png)

请详细描述，是在浏览器中播放不了，还是输入关键字无法触发。

请点击语音包并点击 Play 进行测试，查看是否有声音：
![image](https://user-images.githubusercontent.com/62641267/187279347-c8fad8b6-23c6-40c2-a94f-83773fce8749.png)

**Comment by hansjohn** [comment]
点play播放不了

**Comment by hansjohn** [comment]
懂了,用"导入"导入语音包,不能直接解压到目录里面
